module.exports = new Map([
  ['Quelle langue les conseillers fédéraux parlent-ils en séance ?', 'Chacun s’exprime dans sa langue.'],
  ['Qui est président de la Confédération en 2018 ?', 'Alain Berset'],
  ['Quelle est la durée du mandat du président de la Confédération ?', '1 an'],
  ['Comment le nouveau conseiller fédéral s’appelle-t-il ?', 'Ignazio Cassis'],
  ['Combien de femmes ont été conseillères fédérales jusqu‘ici ?', '7'],
  ['Comment s’appelait la première femme à siéger au Conseil fédéral ?', 'Elisabeth Kopp'],
  ['Qui élit les conseillers fédéraux ?', 'Le Parlement'],
  ['Combien gagne un conseiller fédéral ?', 'Env. 450 000 francs'],
  ['Pourquoi les conseillers fédéraux se vouvoient-ils en séance ?', 'Pour bien distinguer le dossier de la personne qui le traite.'],
  ['Pourquoi n’y a-t-il pas d’Internet dans la salle de séances du Conseil fédéral ?', 'Pour des raisons de sécurité'],
  ['Combien de dossiers le Conseil fédéral traite-t-il en moyenne chaque année ?', 'Plus de 2000'],
  ['Quelle est la durée moyenne d’une séance du Conseil fédéral ?', 'Trois à quatre heures'],
  ['Quel département la conseillère fédérale Simonetta Sommaruga dirige-t-elle ?', 'Département fédéral de justice et police'],
  ['Qui a passé le plus d’années au sein du Conseil fédéral ?', 'Doris Leuthard'],
  ['Le plus jeune conseiller fédéral que la Suisse ait connu avait 31 ans au moment de son élection. Qui était-ce ?', 'Numa Droz'],
  ['Qui le Conseil fédéral rencontre-t-il dans le cadre des entretiens de Watteville ?', 'La présidence des partis et des groupes parlementaires représentés au sein du Conseil fédéral'],
  ['Quels sont les partis représentés au sein du Conseil fédéral ?', 'UDC, PLR, PDC, PS'],
  ['Quel conseiller fédéral a été pris d’un fou rire dans une déclaration concernant la viande des Grisons ?', 'Hans-Rudolf Merz'],
])
